### ISSUE TITLE
Support dynamic element names

### ISSUE THREAD

**Issue by utkarshkukreti** [utkarshkukreti/markup.rs#11]
Currently there's no way to turn:

    let name = "foo";

into

    <foo></foo>

without messing with `markup::raw()`.

Looking for suggestions for syntax to use for this; I can't think of any elegant one right now.

**Comment by ZaneHannanAU** [comment]
syntax could be ({name})[whatever="value", etc] {}, or perhaps enum struct thing ...

**Comment by utkarshkukreti** [comment]
That's interesting. It could also be angle brackets: `<{name}>[whatever ...] {}`.

**Comment by miguelcaravantes** [comment]
This feature would be nice
