### ISSUE TITLE
Non-identifier attribute names

### ISSUE THREAD

**Issue by 17dec** [utkarshkukreti/markup.rs#2]
Thanks for this crate - I'm loving its elegant and simple design.

Is there a way to set attributes that aren't rust identifiers? For example:

```rust
markup::define! {
    Hello {
        // "type" is a keyword, so this fails
        input[type="number"]
        // '-' isn't allowed in an identifier
        br[data-id=1]
    }
}
```

Supporting string literals as attribute names might be a clean way to solve this.

**Comment by utkarshkukreti** [comment]
I'm glad you like it!

A function to parse this kind of thing already existed; not sure how I forgot to use it here earlier. Putting `type` and `data-id` in quotes should now work:

```
markup::define! {
    Hello {
        // "type" is a keyword, so this fails
        input["type"="number"]
        // '-' isn't allowed in an identifier
        br["data-id"=1]
    }
}
```

Let me know if you still have issues with this.

**Comment by 17dec** [comment]
Works, thanks!

**Comment by utkarshkukreti** [comment]
I improved this further by making the parser treat keywords like they're identifiers. You can do `input[type = "number"]` now as of version 0.1.4!
