### ISSUE TITLE
Allow template arguments to be documented

### ISSUE THREAD

**Issue by ssokolow** [utkarshkukreti/markup.rs#21]
Currently, if I attempt to attach a doc comment to a template argument, like this:

```rust
        /// Used for CSS/JS cache-busting
        build_timestamp: &'static str,
```

...I get the following error:

```
error: expected identifier
  --> src/templates.rs:58:9
   |
58 |         /// Used for CSS/JS cache-busting
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm left having to manually add an `Arguments` section containing a bulleted list to the documentation block for the template as a whole, resulting in this needlessly redundant and typo-prone output:

![Screenshot 2022-05-06 at 05-22-16 HttpError](https://user-images.githubusercontent.com/46915/167072380-b2c4a498-3d8a-4f09-909b-9a839636b211.png)

**Comment by utkarshkukreti** [comment]
I've implemented this in https://github.com/utkarshkukreti/markup.rs/commit/45327272008c74090fa701ee26ff52d55fca9301, please let me know if it works for you.

**Comment by ssokolow** [comment]
Looks good. :)

![Screenshot 2022-05-11 at 05-59-08 HttpError](https://user-images.githubusercontent.com/46915/167779272-29acf5a5-6e24-4be8-85f0-1cea9c42cf36.png)
