### ISSUE TITLE
Can't destructure in Markup

### ISSUE THREAD

**Issue by edward-shen** [utkarshkukreti/markup.rs#3]
Hey!

I'm trying to destructure an struct in a markup parameter:
```rust
Foo(Bar {x, y, z}: Bar) {
    p { {x} }
}
``` 

But the compiler's expecting an `:` where the destructure is occuring.

For reference, I can do this in a normal function:
```rust
fn Foo(Bar {x, y, z}: Bar) { // ... }
```

Is this a bug or an unsupported feature?

**Comment by edward-shen** [comment]
I guess a simple workaround would be to destructure at the next available level, but I think this would be a great feature to add!

**Comment by utkarshkukreti** [comment]
This is because markup creates a struct for the arguments. If you use a pattern on the left side, there's no way to know what the struct field should be called.

**Comment by utkarshkukreti** [comment]
Closing as resolved. If you have any other questions, feel free to ask.
