### ISSUE TITLE
Can not add attributes to definitions

### ISSUE THREAD

**Issue by L-as** [utkarshkukreti/markup.rs#8]
E.g. this is not allowed:
```rust
markup::define! {
	#[derive(Clone)]
	MyMarkup {
		"hi"
	}
}
```

I think this affects documentation comments too.

**Comment by utkarshkukreti** [comment]
@L-as I've not needed this yet, but it was a simple change so I added it. Check [this](https://github.com/utkarshkukreti/markup.rs/commit/22610cd74e4cefb1dd5afb8448621d9179f797b6#diff-696a6b170ca144510d09c1fdb8212875R18-R19) out. Let me know if anything doesn't work.
