### ISSUE TITLE
Hyphenated attributes throw "error: expected `=`"

### ISSUE THREAD

**Issue by niallrr** [utkarshkukreti/markup.rs#9]
Hyphenated attributes produce the following error. This is important for being able to use Bootstrap.

```rust
button [
    type="button",
    class="btn btn-circle btn-dual-secondary d-lg-none align-v-r",
    data-toggle="layout",
    data-action="sidebar_close"
    ]
    {
        i [class="fa fa-times text-danger"]
    }
```

Throws the error
```bash
error: expected `=`
   --> src/t_base.rs:115:29
    |
115 |                         data-toggle="layout",
    |  
```

**Comment by niallrr** [comment]
Just found a workaround
```rust
    "data-toggle"="layout",
    "data-action"="sidebar_close"
```

**Comment by utkarshkukreti** [comment]
Hi, yes, that's the right way. Proc macros in Rust work with Rust tokens, so there's no way to distinguish between `data - toggle = "layout"` and `data-toggle = "layout"`, which is why I allow string literals on the left of `=`.
